"""
SQLAlchemy + GeoAlchemy2 Models for PostgreSQL + PostGIS
Cybercrime Predictive Analytics Framework (Problem Statement ID 26184)
"""
from datetime import datetime, timezone
from sqlalchemy import (
    Column,
    Integer,
    String,
    Float,
    DateTime,
    Text,
    Index,
    func
)
from geoalchemy2 import Geometry
from database.connection import Base


class CybercrimeEvent(Base):
    """
    Core database table for authorized/anonymized cybercrime complaint events.
    Includes PostGIS POINT geometry (SRID 4326) with WGS 84 coordinate reference.
    Coordinates must be formatted as: POINT(longitude latitude).
    """
    __tablename__ = "cybercrime_events"

    id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    case_id = Column(String(64), unique=True, nullable=False, index=True, doc="Sanitized unique complaint reference")
    complaint_timestamp = Column(DateTime, nullable=False, index=True, doc="Timestamp when incident occurred / reported")
    crime_type = Column(String(64), nullable=False, index=True, doc="Standardized crime attack taxonomy")
    fraud_amount = Column(Float, nullable=False, doc="Financial loss amount in INR")
    reported_by_authority = Column(Integer, default=0, doc="1 if filed by law enforcement/bank, 0 if citizen")
    victim_state = Column(String(64), nullable=True, doc="State name of incident")
    victim_district = Column(String(64), nullable=True, index=True, doc="District name of incident")
    victim_area = Column(String(128), nullable=True, doc="Sub-locality or beat area")
    victim_area_id = Column(String(64), nullable=True, doc="Administrative area reference code")
    latitude = Column(Float, nullable=True, doc="WGS 84 latitude [-90, 90]")
    longitude = Column(Float, nullable=True, doc="WGS 84 longitude [-180, 180]")
    
    # PostGIS spatial point geometry (SRID 4326: WGS 84 longitude/latitude)
    # Stored as POINT(longitude latitude)
    location = Column(
        Geometry(geometry_type="POINT", srid=4326, spatial_index=True),
        nullable=True,
        doc="PostGIS POINT(longitude latitude) spatial geometry in SRID 4326"
    )
    
    # Historical linkage flag from cleaned dataset
    is_linked_to_withdrawal = Column(Integer, default=0, doc="Historical cashout linkage indicator")
    
    # Target outcome if available from ground truth
    future_withdrawal = Column(Integer, nullable=True, doc="Ground truth binary cashout label (null for unseen)")
    
    # Record metadata
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), doc="Database insertion timestamp")

    __table_args__ = (
        Index("ix_events_district_timestamp", "victim_district", "complaint_timestamp"),
        Index("ix_events_crime_timestamp", "crime_type", "complaint_timestamp"),
    )

    def __repr__(self) -> str:
        return f"<CybercrimeEvent(case_id='{self.case_id}', crime='{self.crime_type}', district='{self.victim_district}')>"


class PredictionResult(Base):
    """
    Storage table for model inference outputs generated by Phase 11 / Phase 12.
    Stores safe operational intelligence, risk categories, and optional spatial points.
    Strictly excludes all raw inputs, passwords, PINs, OTPs, or PII.
    """
    __tablename__ = "prediction_results"

    id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    prediction_reference = Column(String(64), nullable=False, index=True, doc="Unique complaint or request reference")
    prediction_timestamp = Column(DateTime, nullable=False, index=True, doc="Timestamp of inference request")
    predicted_probability = Column(Float, nullable=False, doc="Continuous future cashout probability [0.0, 1.0]")
    risk_score = Column(Integer, nullable=False, doc="Phase 9 calibrated risk score [0, 100]")
    risk_category = Column(String(32), nullable=False, index=True, doc="Risk tier: LOW, MODERATE, HIGH, CRITICAL")
    operational_interpretation = Column(Text, nullable=True, doc="Standardized guidance for human analyst")
    model_version = Column(String(64), nullable=False, doc="Deterministic model version fingerprint")
    
    # Optional spatial fields for geographic aggregation
    latitude = Column(Float, nullable=True, doc="Complaint latitude")
    longitude = Column(Float, nullable=True, doc="Complaint longitude")
    location = Column(
        Geometry(geometry_type="POINT", srid=4326, spatial_index=True),
        nullable=True,
        doc="PostGIS POINT(longitude latitude) for spatial intelligence"
    )
    victim_district = Column(String(64), nullable=True, index=True, doc="Incident district")
    crime_type = Column(String(64), nullable=True, doc="Incident crime type")
    
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), doc="Insertion timestamp")

    __table_args__ = (
        Index("ix_predictions_category_time", "risk_category", "prediction_timestamp"),
        Index("ix_predictions_district_risk", "victim_district", "risk_score"),
    )

    def __repr__(self) -> str:
        return f"<PredictionResult(ref='{self.prediction_reference}', score={self.risk_score}, category='{self.risk_category}')>"


class CybercrimeAlert(Base):
    """
    Storage table for analytical cybercrime alerts generated by Phase 16 Alert Engine.
    Stores operational risk signals and spatial hotspot alerts.
    Does NOT store sensitive PII, account numbers, card numbers, or automated punitive actions.
    """
    __tablename__ = "cybercrime_alerts"

    id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    alert_id = Column(String(64), unique=True, nullable=False, index=True, doc="Unique analytical alert reference (e.g., ALT-000001)")
    alert_type = Column(String(64), nullable=False, index=True, doc="Alert type (e.g., CRITICAL_RISK_LOCATION, HOTSPOT_CRITICAL_RISK)")
    severity = Column(String(32), nullable=False, index=True, doc="Severity tier: LOW, MODERATE, HIGH, CRITICAL")
    status = Column(String(32), nullable=False, default="NEW", index=True, doc="Status: NEW, ACKNOWLEDGED, IN_REVIEW, RESOLVED, DISMISSED")
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True, doc="Generation timestamp")
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc), doc="Last update timestamp")
    
    # Analytical provenance
    prediction_reference = Column(String(64), nullable=True, doc="Linked prediction identifier")
    hotspot_id = Column(String(64), nullable=True, index=True, doc="Linked Phase 14 DBSCAN cluster ID")
    risk_score = Column(Integer, nullable=False, doc="Calculated risk score [0-100]")
    predicted_probability = Column(Float, nullable=True, doc="Predicted withdrawal probability [0.0-1.0]")
    event_count = Column(Integer, nullable=True, doc="Clustered event count")
    dominant_category = Column(String(64), nullable=True, doc="Dominant crime taxonomy group")
    time_window_start = Column(DateTime, nullable=True, doc="Temporal window start")
    time_window_end = Column(DateTime, nullable=True, doc="Temporal window end")
    operational_message = Column(Text, nullable=False, doc="Operational interpretation guidance")
    human_review_required = Column(Integer, default=1, doc="1 if authorized human review is required, else 0")
    model_version = Column(String(64), nullable=True, doc="Model artifact version fingerprint")

    # Optional spatial point for map display
    latitude = Column(Float, nullable=True, doc="Centroid or complaint latitude")
    longitude = Column(Float, nullable=True, doc="Centroid or complaint longitude")
    location = Column(
        Geometry(geometry_type="POINT", srid=4326, spatial_index=True),
        nullable=True,
        doc="PostGIS POINT(longitude latitude) for map visualization"
    )

    __table_args__ = (
        Index("ix_alerts_severity_status", "severity", "status"),
        Index("ix_alerts_type_hotspot", "alert_type", "hotspot_id"),
        Index("ix_alerts_created_at_desc", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<CybercrimeAlert(alert_id='{self.alert_id}', type='{self.alert_type}', severity='{self.severity}', status='{self.status}')>"


class AlertAuditLog(Base):
    """
    Immutable audit trail recording all alert status transitions and analyst actions.
    """
    __tablename__ = "alert_audit_log"

    id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    alert_id = Column(String(64), nullable=False, index=True, doc="Referenced alert ID")
    action = Column(String(64), nullable=False, doc="Action performed: GENERATE, ACKNOWLEDGE, REVIEW, RESOLVE, DISMISS")
    previous_status = Column(String(32), nullable=True, doc="Status prior to action")
    new_status = Column(String(32), nullable=False, doc="Status resulting from action")
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True, doc="Timestamp of action")
    actor_type = Column(String(32), default="SYSTEM", doc="Actor classification: SYSTEM or AUTHORIZED_USER")
    notes = Column(Text, nullable=True, doc="Analyst rationale or operational remarks")

    __table_args__ = (
        Index("ix_audit_alert_timestamp", "alert_id", "timestamp"),
    )

    def __repr__(self) -> str:
        return f"<AlertAuditLog(alert_id='{self.alert_id}', action='{self.action}', {self.previous_status}->{self.new_status})>"
